version: "3.8"
services:
  ## Databases ##
  db_dojo:
    image: rxinui/db_dojo:latest
    build:
      context: ./services/db_dojo/
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: oui
    networks:
      intdojonet:
        ipv4_address: 172.20.0.2
  ## System components ##
  rabbitmq:
    image: rabbitmq:3.9.13
    ports:
      - 5672:5672
    networks:
      intdojonet:
        ipv4_address: 172.20.0.30
  rportd:
    image: rxinui/rportd
    build:
      context: ./services/rportd/
    tty: true
    hostname: .myrport.com
    ports:
      - 9050:5000 #api
      - 9080:8000 #client
      - 20000-20050:20000-20050 #range of tunnels
    environment:
      - RPORTD_AUTH_USER="admin"
      - RPORTD_AUTH_PASSWORD="shihan"
      - RPORTD_API_PORT=5000
      - RPORTD_CLIENT_PORT=8000
      - TUNNEL_RANGE_PORT="20000-20050"
    networks:
      intdojonet:
        ipv4_address: 172.20.0.31
  ## APIs ##
  api_auth:
    depends_on:
      - db_dojo
    image: rxinui/api_auth:latest
    build:
      context: ./services/api_auth/
    ports:
      - 8000:80
    environment:
      API_AUTH_HOST: 172.20.0.10
      API_AUTH_PORT: 80
      API_AUTH_SESSION_SECRET: "bhkKyq8yEaHd49PD"
      API_AUTH_JWT_SECRET: "q@M&P8gXLJrh47&d"
      API_DB_HOST: 172.20.0.2
      API_DB_USER: sifu
      API_DB_PASSWORD: sifu
      API_DB_DATABASE: dojo_auth
      API_DB_CONNECTION_LIMIT: 10

    networks:
      intdojonet:
        ipv4_address: 172.20.0.10
  api_vbox:
    depends_on:
      - db_dojo
      - rabbitmq
    image: rxinui/api_vbox:latest
    build:
      context: ./services/api_vbox/
    ports:
      - 8001:80
    environment:
      API_VBOX_HOST: 172.20.0.11
      API_VBOX_PORT: 80
      API_VBOX_EXECMODE: container
      API_VBOX_RABBITMQ_HOST: 172.20.0.30
      API_VBOX_RABBITMQ_PORT: 5672
      API_VBOX_USERS_REQUEST_QUEUE: api_vbox.users.request_queue
      API_AUTH_URL: http://172.20.0.10
    networks:
      intdojonet:
        ipv4_address: 172.20.0.11
networks:
  intdojonet:
    name: intdojonet
    ipam:
      driver: default
      config:
        ## Range of IP
        # FROM .2 to .9 --> databases
        # FROM .10 to .29 --> API Services 
        # FROM .30 to .49 --> System Components 
        - subnet: "172.20.0.0/26" # API global internal network - dev