version: '3.8'

services:

  db:
    image: rxinui/db_dojo:latest
    build: 
      context: .
    ports:
      - 3306:3306
    volumes:
      - "./initdb.d/:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: oui
    networks:
      default:

networks:
  default:
    ipam:
      driver: default