version: '3.8'

services:

  db:
    image: rxinui/db_dojo:latest
    build: 
      context: .
    ports:
      - 3306:3306
    volumes:
      - "./volume/initdb.d/:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: oui
      MARIADB_USER: sifu
      MARIADB_PASSWORD: sifu
      MARIADB_DATABASE: dojo