version: '3.8'

services:

  db:
    image: rxinui/db_dojo:0.1
    build: 
      context: .
    ports:
      - 3306:3306
    volumes:
      - "./volume/initdb.d/:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root


