version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.13
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672
    environment:
      - RABBITMQ_HOST="0.0.0.0"
      - RABBITMQ_PORT="5672"
