name: Build and test services independently
on:
  push:
    branches: [main, pfe45_ci_cd]
  pull_request:
    branches: [main, develop]
env:
  DB_DOJO_VERSION: 0.1.1
  API_AUTH_VERSION: 0.1.1
  API_VBOX_VERSION: 0.1.1
  NODE_ENV: development
jobs:
  call-commitlinter:
    runs-on: ubuntu-20.04
    steps:
      - name: Lint branch newest commit format
        id: lintResult
        uses: Rxinui/commitlinter@main
        with:
          commitTags: "new,fix,doc,ref,wip"
          commitIssueId: "PFE"
  api_vbox-static-security:
    needs: call-commitlinter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: 42Crunch REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@96228d9c48873fe001354047d47fb62be42abeb1
        with:
          api-token: ${{ secrets.API_TOKEN_42CRUNCH }}
          min-score: 50
          upload-to-code-scanning: true
  build-api_vbox:
    needs: api_vbox-static-security
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test services/api_vbox/ with pytest
        run: |
          cd $GITHUB_WORKSPACE/services/api_vbox/ && pytest test/unit/;
          cd $GITHUB_WORKSPACE
      - name: Lint with pylint
        run: |
          find services/api_vbox/ -name '*.py' -exec pylint {} --rcfile $GITHUB_WORKSPACE/.pylintrc \;

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/api_vbox/
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api_vbox:${{ env.API_VBOX_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api_vbox:latest
  build-db_dojo:
    needs: call-commitlinter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/db_dojo/
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/db_dojo:${{ env.DB_DOJO_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/db_dojo:latest
  build-api_auth:
    needs: call-commitlinter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/api_auth/
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api_auth:${{ env.API_AUTH_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api_auth:latest
