# CD services aims to deploy all services Docker image to (pre-)prod
# Logicial view of the CD is :
#
#

name: "[Reusable] Continuous deployment of services with Git through SSH"
on:
  workflow_call:
    inputs:
      deploy-branch:
        required: true
        default: develop
        type: string
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy project
    steps:
      - name: Use of Rxinui/ssh-deploy-repo-action to deploy
        uses: Rxinui/ssh-deploy-repo-action@v1.1
        with:
          ssh-user: ubuntu
          ssh-password: ${{ secrets.OVH_ns343000_PASSWORD }}
          ssh-domain: ${{ secrets.OVH_ns343000_DOMAIN }}
          git-clone-by: ssh
          target-branch: ${{ inputs.deploy-branch }}
          target-directory: /opt/pfe/DojoPlateforme
          pre-command: |
            cd /opt/pfe/DojoPlateforme &&
            ./setup.sh stop
          post-command: ./setup.sh start --build
            


  