# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: API api_vbox [Python]

on:
  push:
    branches: [main, develop, pfe9_ci_security_42crunch]
  pull_request:
    branches: [main, develop]

jobs:
  call-commitlinter:
    runs-on: ubuntu-20.04
    steps:
      - name: Lint branch newest commit format
        id: lintResult
        uses: Rxinui/commitlinter@v1.1
        with:
          commitTags: "new,fix,doc,ref,wip"
          commitIssueId: "PFE"
  build-api-vbox:
    needs: call-commitlinter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test api/api_vbox/ with pytest
        run: |
          cd $GITHUB_WORKSPACE/api/api_vbox/ && pytest; 
          cd $GITHUB_WORKSPACE
      - name: Lint with pylint
        run: |
          find api/api_vbox/ -name '*.py' -exec pylint {} --rcfile $GITHUB_WORKSPACE/.pylintrc \;
  rest-api-static-security-testing:
    needs: call-commitlinter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: 42Crunch REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@96228d9c48873fe001354047d47fb62be42abeb1
        with:
          api-token: ${{ secrets.API_TOKEN_42CRUNCH }}
          min-score: 75
          upload-to-code-scanning: true


