name: Pre-production pipeline test
on:
  push:
    branches: [main, pfe26_workflow_virtualbox_runner]
  pull_request:
    branches: [main]
env:
  DB_DOJO_VERSION: 0.1.1
  NODE_ENV: development
jobs:
  test-preprod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies required by the project
        run: ./.github/scripts/install_linux_dep.sh
        shell: bash
      - name: Download resources from production web repositories
        run:  wget -O ./system/virtualbox/ovf/pmint_box_dev.ova https://ns343000.ip-5-39-74.eu/repos/test/virtualbox/ovf/pmint_box_dev.ova
      - name: Create a new VM by importing .ova file
        run: VBoxManage import ./system/virtualbox/ovf/pmint_box_dev.ova --vsys 0 --vmname test_box --basefolder ./system/virtualbox/vms/
      - name: List VMs
        run: VBoxManage list vms -l

      